### ISSUE TITLE
Hit F5

### ISSUE THREAD

**Issue by Bhaney44** [algorandfoundation/algokit-beaker-playground-template#11]
I am on a Mac and don't have an F5 key. Is there another way to launch the `helloworld.py` contract?

**Comment by tristanmenzel** [comment]
You can achieve the same thing by opening the `Run` menu and selecting `Start Debugging`

![image](https://github.com/algorandfoundation/algokit-beaker-playground-template/assets/6836315/987437b6-9ec4-4a46-82f2-dfc2daa05cdf)

**Comment by Bhaney44** [comment]
I ran 

`Python3 FILE_NAME.py`

Sorry for the noob error, I was in the wrong directory when I initially tried.
